import * as engine from './engine.mjs';

export function registerFinanceActions(executor) {
  if (!executor || typeof executor.registerHandler !== 'function') {
    throw new Error('ActionExecutor with registerHandler is required');
  }

  executor
    .registerHandler('finance_account:create', ({ dialect, ctx, input }) => engine.createAccount(dialect, ctx, input))
    .registerHandler('finance_account:update', ({ dialect, ctx, input }) => engine.updateAccount(dialect, ctx, input))
    .registerHandler('finance_account:deactivate', ({ dialect, ctx, input }) => engine.deactivateAccount(dialect, ctx, input))
    .registerHandler('finance_journal:create', ({ dialect, ctx, input }) => engine.createJournal(dialect, ctx, input))
    .registerHandler('finance_document:create', ({ dialect, ctx, input }) => engine.createDocument(dialect, ctx, input))
    .registerHandler('finance_document:submit', ({ dialect, ctx, input }) => engine.submitDocument(dialect, ctx, input))
    .registerHandler('finance_document:approve', ({ dialect, ctx, input }) => engine.approveDocument(dialect, ctx, input))
    .registerHandler('finance_document:post', ({ dialect, ctx, input }) => engine.postDocument(dialect, ctx, input))
    .registerHandler('finance_document:reverse', ({ dialect, ctx, input }) => engine.reverseDocument(dialect, ctx, input))
    .registerHandler('finance_document:amend', ({ dialect, ctx, input }) => engine.amendDocument(dialect, ctx, input))
    .registerHandler('finance_document:cancel', ({ dialect, ctx, input }) => engine.cancelDocument(dialect, ctx, input))
    .registerHandler('finance_period:open', ({ dialect, ctx, input }) => engine.openPeriod(dialect, ctx, input))
    .registerHandler('finance_period:soft_close', ({ dialect, ctx, input }) => engine.softClosePeriod(dialect, ctx, input))
    .registerHandler('finance_period:hard_close', ({ dialect, ctx, input }) => engine.hardClosePeriod(dialect, ctx, input))
    .registerHandler('finance_period:reopen', ({ dialect, ctx, input }) => engine.reopenPeriod(dialect, ctx, input))
    .registerHandler('finance_dimension:create', ({ dialect, ctx, input }) => engine.createDimension(dialect, ctx, input))
    .registerHandler('finance_dimension:value_create', ({ dialect, ctx, input }) => engine.createDimensionValue(dialect, ctx, input))
    .registerHandler('finance_dimension:policy_set', ({ dialect, ctx, input }) => engine.setAccountDimensionPolicy(dialect, ctx, input))
    .registerHandler('finance_journal:verify_integrity', ({ dialect, ctx, input }) => engine.verifyHashChain(dialect, ctx, input))
    .registerHandler('finance_currency:upsert', ({ dialect, ctx, input }) => engine.upsertCurrency(dialect, ctx, input))
    .registerHandler('finance_exchange_rate:upsert', ({ dialect, ctx, input }) => engine.upsertExchangeRate(dialect, ctx, input))
    .registerHandler('finance_fx:revalue', ({ dialect, ctx, input }) => engine.revalueForeignBalances(dialect, ctx, input))
    .registerHandler('finance_tax:create', ({ dialect, ctx, input }) => engine.createTax(dialect, ctx, input))
    .registerHandler('finance_tax:repartition_set', ({ dialect, ctx, input }) => engine.setTaxRepartitionLines(dialect, ctx, input))
    .registerHandler('finance_tax:quote', ({ dialect, ctx, input }) => engine.computeTax(dialect, ctx, input))
    .registerHandler('finance_withholding:category_create', ({ dialect, ctx, input }) => engine.createWithholdingCategory(dialect, ctx, input))
    .registerHandler('finance_withholding:evaluate', ({ dialect, ctx, input }) => engine.evaluateWithholding(dialect, ctx, input))
    .registerHandler('finance_fiscal_position:create', ({ dialect, ctx, input }) => engine.createFiscalPosition(dialect, ctx, input))
    .registerHandler('finance_fiscal_position:map_tax', ({ dialect, ctx, input }) => engine.mapFiscalPositionTax(dialect, ctx, input))
    .registerHandler('finance_fiscal_position:map_account', ({ dialect, ctx, input }) => engine.mapFiscalPositionAccount(dialect, ctx, input))
    .registerHandler('finance_localization:install', ({ dialect, ctx, input }) => engine.installLocalizationPack(dialect, ctx, input))
    .registerHandler('finance_due_schedule:set', ({ dialect, ctx, input }) => engine.setDueSchedule(dialect, ctx, input))
    .registerHandler('finance_ar:open_items', ({ dialect, ctx, input }) => engine.getCustomerOpenItems(dialect, ctx, input))
    .registerHandler('finance_ar:aging', ({ dialect, ctx, input }) => engine.getCustomerAging(dialect, ctx, input))
    .registerHandler('finance_ap:open_items', ({ dialect, ctx, input }) => engine.getSupplierOpenItems(dialect, ctx, input))
    .registerHandler('finance_ap:aging', ({ dialect, ctx, input }) => engine.getSupplierAging(dialect, ctx, input))
    .registerHandler('finance_ap:hold', ({ dialect, ctx, input }) => engine.holdPayment(dialect, ctx, input))
    .registerHandler('finance_ap:release_hold', ({ dialect, ctx, input }) => engine.releasePaymentHold(dialect, ctx, input))
    .registerHandler('finance_authority_limit:set', ({ dialect, ctx, input }) => engine.setApprovalAuthorityLimit(dialect, ctx, input))
    .registerHandler('finance_payment:create', ({ dialect, ctx, input }) => engine.createPayment(dialect, ctx, input))
    .registerHandler('finance_payment:post', ({ dialect, ctx, input }) => engine.postPayment(dialect, ctx, input))
    .registerHandler('finance_payment:reverse', ({ dialect, ctx, input }) => engine.reversePaymentAction(dialect, ctx, input))
    .registerHandler('finance_payment:allocate', ({ dialect, ctx, input }) => engine.allocatePayment(dialect, ctx, input))
    .registerHandler('finance_payment:unallocate', ({ dialect, ctx, input }) => engine.unallocatePayment(dialect, ctx, input))
    .registerHandler('finance_document:write_off', ({ dialect, ctx, input }) => engine.writeOffOpenItem(dialect, ctx, input))
    .registerHandler('finance_reconciliation:open_session', ({ dialect, ctx, input }) => engine.openReconciliationSession(dialect, ctx, input))
    .registerHandler('finance_reconciliation:confirm_match', ({ dialect, ctx, input }) => engine.confirmReconciliationMatch(dialect, ctx, input))
    .registerHandler('finance_reconciliation:undo_match', ({ dialect, ctx, input }) => engine.undoReconciliationMatch(dialect, ctx, input))
    .registerHandler('finance_reconciliation:close_session', ({ dialect, ctx, input }) => engine.closeReconciliationSession(dialect, ctx, input))
    .registerHandler('finance_bank_account:create', ({ dialect, ctx, input }) => engine.createBankAccount(dialect, ctx, input))
    .registerHandler('finance_bank_match_rule:create', ({ dialect, ctx, input }) => engine.createBankMatchRule(dialect, ctx, input))
    .registerHandler('finance_bank_statement:import', ({ dialect, ctx, input }) => engine.importBankStatement(dialect, ctx, input))
    .registerHandler('finance_bank_statement:match', ({ dialect, ctx, input }) => engine.matchBankStatementLine(dialect, ctx, input))
    .registerHandler('finance_bank_statement:manual_reconcile', ({ dialect, ctx, input }) => engine.manualReconcileBankLine(dialect, ctx, input))
    .registerHandler('finance_bank_statement:record_difference', ({ dialect, ctx, input }) => engine.recordBankDifference(dialect, ctx, input))
    .registerHandler('finance_bank_statement:unreconcile', ({ dialect, ctx, input }) => engine.unreconcileBankLine(dialect, ctx, input))
    .registerHandler('finance_cashbox:create', ({ dialect, ctx, input }) => engine.createCashbox(dialect, ctx, input))
    .registerHandler('finance_cash_shift:open', ({ dialect, ctx, input }) => engine.openCashShift(dialect, ctx, input))
    .registerHandler('finance_cash_shift:count', ({ dialect, ctx, input }) => engine.recordCashCount(dialect, ctx, input))
    .registerHandler('finance_cash_shift:close', ({ dialect, ctx, input }) => engine.closeCashShift(dialect, ctx, input))
    .registerHandler('finance_payment_term:create', ({ dialect, ctx, input }) => engine.createPaymentTermTemplate(dialect, ctx, input))
    .registerHandler('finance_payment_term:generate_schedule', ({ dialect, ctx, input }) => engine.generateDueScheduleFromTerm(dialect, ctx, input))
    .registerHandler('finance_credit_profile:set', ({ dialect, ctx, input }) => engine.setCreditProfile(dialect, ctx, input))
    .registerHandler('finance_credit:hold', ({ dialect, ctx, input }) => engine.holdCredit(dialect, ctx, input))
    .registerHandler('finance_credit:release_hold', ({ dialect, ctx, input }) => engine.releaseCreditHold(dialect, ctx, input))
    .registerHandler('finance_credit:exposure', ({ dialect, ctx, input }) => engine.getCreditExposure(dialect, ctx, input))
    .registerHandler('finance_budget:create', ({ dialect, ctx, input }) => engine.createBudget(dialect, ctx, input))
    .registerHandler('finance_budget:submit', ({ dialect, ctx, input }) => engine.submitBudget(dialect, ctx, input))
    .registerHandler('finance_budget:approve', ({ dialect, ctx, input }) => engine.approveBudget(dialect, ctx, input))
    .registerHandler('finance_budget:reject', ({ dialect, ctx, input }) => engine.rejectBudget(dialect, ctx, input))
    .registerHandler('finance_budget:revise', ({ dialect, ctx, input }) => engine.reviseBudget(dialect, ctx, input))
    .registerHandler('finance_budget:variance', ({ dialect, ctx, input }) => engine.getBudgetVariance(dialect, ctx, input))
    .registerHandler('finance_expense_claim:create', ({ dialect, ctx, input }) => engine.createExpenseClaim(dialect, ctx, input))
    .registerHandler('finance_expense_claim:submit', ({ dialect, ctx, input }) => engine.submitExpenseClaim(dialect, ctx, input))
    .registerHandler('finance_expense_claim:approve', ({ dialect, ctx, input }) => engine.approveExpenseClaim(dialect, ctx, input))
    .registerHandler('finance_expense_claim:reject', ({ dialect, ctx, input }) => engine.rejectExpenseClaim(dialect, ctx, input))
    .registerHandler('finance_employee_advance:issue', ({ dialect, ctx, input }) => engine.issueEmployeeAdvance(dialect, ctx, input))
    .registerHandler('finance_employee_advance:settle', ({ dialect, ctx, input }) => engine.settleAdvanceAgainstClaim(dialect, ctx, input))
    .registerHandler('finance_report:run', ({ dialect, ctx, input }) => engine.runReport(dialect, ctx, input))
    .registerHandler('finance_report:snapshot', ({ dialect, ctx, input }) => engine.snapshotReport(dialect, ctx, input))
    .registerHandler('finance_asset_category:create', ({ dialect, ctx, input }) => engine.createAssetCategory(dialect, ctx, input))
    .registerHandler('finance_asset:capitalize', ({ dialect, ctx, input }) => engine.capitalizeAsset(dialect, ctx, input))
    .registerHandler('finance_asset:post_depreciation', ({ dialect, ctx, input }) => engine.postAssetDepreciation(dialect, ctx, input))
    .registerHandler('finance_asset:dispose', ({ dialect, ctx, input }) => engine.disposeAsset(dialect, ctx, input))
    .registerHandler('finance_migration:import_accounts', ({ dialect, ctx, input }) => engine.migrateLegacyAccounts(dialect, ctx, input))
    .registerHandler('finance_migration:import_moves', ({ dialect, ctx, input }) => engine.migrateLegacyMoves(dialect, ctx, input))
    .registerHandler('finance_migration:reconcile', ({ dialect, ctx, input }) => engine.reconcileMigrationTrialBalance(dialect, ctx, input))
    .registerHandler('finance_migration:rollback_run', ({ dialect, ctx, input }) => engine.rollbackMigrationRun(dialect, ctx, input))
    .registerHandler('finance_migration:quarantine_list', ({ dialect, ctx, input }) => engine.getMigrationQuarantine(dialect, ctx, input))
    .registerHandler('finance_source_fact:post', ({ dialect, ctx, input }) => engine.postSourceFact(dialect, ctx, input))
    .registerHandler('finance_source_fact:reverse', ({ dialect, ctx, input }) => engine.reverseSourceFact(dialect, ctx, input))
    .registerHandler('finance_cutover:transition', ({ dialect, ctx, input }) => engine.transitionCutoverState(dialect, ctx, input))
    .registerHandler('finance_cutover:get_status', ({ dialect, ctx }) => ({ state: engine.getCutoverState(dialect, ctx.companyId) }))
    .registerHandler('finance_lock:set', ({ dialect, ctx, input }) => engine.setLockDate(dialect, ctx, input))
    .registerHandler('finance_retainage:release', ({ dialect, ctx, input }) => engine.releaseRetainage(dialect, ctx, input));

  return executor;
}

export * from './engine.mjs';
