// BUILD-07C: company-scoped service coverage authority.
'use strict';
const actions = ['service_contract:create','service_contract:validate','service_contract:submit','service_contract:approve','service_contract:activate','service_contract:suspend','service_contract:resume','service_contract:renew','entitlement:policy_create','entitlement:policy_publish','entitlement:evaluate','entitlement:consume','entitlement:reverse','entitlement:override_request','entitlement:override_approve'];
export const migration = { id: '071_service_contracts_entitlements', parent: '070_planning_and_advanced_finance',
  up(db) { db.exec(`
    CREATE TABLE IF NOT EXISTS service_contracts (id TEXT PRIMARY KEY, company_id TEXT NOT NULL, customer_id TEXT NOT NULL, contract_number TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','validated','submitted','approved','active','rejected','suspended','expired','cancelled','renewed','closed')), start_date TEXT NOT NULL,end_date TEXT NOT NULL,response_sla_hours INTEGER,resolution_sla_hours INTEGER,suspension_reason TEXT,cancellation_reason TEXT,created_by TEXT NOT NULL,approved_by TEXT,idempotency_key TEXT UNIQUE,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
    CREATE UNIQUE INDEX IF NOT EXISTS idx_service_contract_number ON service_contracts(company_id,contract_number);
    CREATE TABLE IF NOT EXISTS service_contract_products (contract_id TEXT NOT NULL REFERENCES service_contracts(id),product_id TEXT NOT NULL,PRIMARY KEY(contract_id,product_id));
    CREATE TABLE IF NOT EXISTS service_contract_assets (contract_id TEXT NOT NULL REFERENCES service_contracts(id),asset_id TEXT NOT NULL,PRIMARY KEY(contract_id,asset_id));
    CREATE TABLE IF NOT EXISTS service_contract_sites (contract_id TEXT NOT NULL REFERENCES service_contracts(id),site_id TEXT NOT NULL,PRIMARY KEY(contract_id,site_id));
    CREATE TABLE IF NOT EXISTS service_contract_lines (id TEXT PRIMARY KEY,contract_id TEXT NOT NULL REFERENCES service_contracts(id),description TEXT NOT NULL,quantity REAL NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS service_contract_exclusions (id TEXT PRIMARY KEY,contract_id TEXT NOT NULL REFERENCES service_contracts(id),cause_code TEXT NOT NULL,reason TEXT,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS service_contract_allowances (id TEXT PRIMARY KEY,contract_id TEXT NOT NULL REFERENCES service_contracts(id),allowance_type TEXT NOT NULL,limit_value REAL NOT NULL,consumed_value REAL NOT NULL DEFAULT 0,UNIQUE(contract_id,allowance_type));
    CREATE TABLE IF NOT EXISTS service_contract_renewals (id TEXT PRIMARY KEY,contract_id TEXT NOT NULL REFERENCES service_contracts(id),renewed_contract_id TEXT,renewal_date TEXT NOT NULL,created_by TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS service_contract_history (id TEXT PRIMARY KEY,contract_id TEXT NOT NULL REFERENCES service_contracts(id),from_status TEXT,to_status TEXT NOT NULL,actor_id TEXT NOT NULL,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS entitlement_policies (id TEXT PRIMARY KEY,company_id TEXT NOT NULL,contract_id TEXT NOT NULL REFERENCES service_contracts(id),name TEXT NOT NULL,priority INTEGER NOT NULL DEFAULT 100,status TEXT NOT NULL CHECK(status IN ('draft','validated','approved','published','retired')),visit_limit INTEGER NOT NULL DEFAULT 0,visits_used INTEGER NOT NULL DEFAULT 0,excluded_cause TEXT,response_sla_hours INTEGER,resolution_sla_hours INTEGER,created_by TEXT NOT NULL,approved_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS entitlement_decisions (id TEXT PRIMARY KEY,company_id TEXT NOT NULL,contract_id TEXT,policy_id TEXT,status TEXT NOT NULL,reason_code TEXT,covered_labor REAL NOT NULL DEFAULT 0,covered_parts REAL NOT NULL DEFAULT 0,response_sla_hours INTEGER,resolution_sla_hours INTEGER,source_type TEXT,source_id TEXT,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS entitlement_usage_ledger (id TEXT PRIMARY KEY,company_id TEXT NOT NULL,policy_id TEXT NOT NULL,decision_id TEXT,source_type TEXT,source_id TEXT,idempotency_key TEXT UNIQUE,quantity REAL NOT NULL,reversal_of TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS entitlement_overrides (id TEXT PRIMARY KEY,company_id TEXT NOT NULL,decision_id TEXT NOT NULL,requested_by TEXT NOT NULL,approved_by TEXT,status TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
  `); db.prepare(`INSERT INTO platform_entities (id,module_id,storage_owner,primary_key,label_ar,label_en,section,chatter,fields,relations,scope,lifecycle_policy,query_policy,action_policy,customization_policy,history_policy,api_exposed,migration_owner,created_at,updated_at) VALUES ('service_contract','platform_kernel','platform.service','id','عقد خدمة','Service Contract','service',0,'{}','{}','company','governed','scoped','registered','metadata','audit',1,'071_service_contracts_entitlements',datetime('now'),datetime('now')) ON CONFLICT(id) DO NOTHING`).run(); const insert=db.prepare(`INSERT INTO platform_actions (id,module_id,entity_id,kind,allowed_states,required_permission,required_scope,input_schema,preconditions,transaction_owner,idempotency_policy,sequence_policy,audit_policy,outbox_policy,error_contract,created_at,updated_at) VALUES (?,'platform_kernel','service_contract','domain','[]','platform:db:write','company','{}','[]','platform_action_executor','required','none','required','required','{}',datetime('now'),datetime('now')) ON CONFLICT(id) DO NOTHING`); actions.forEach(a=>insert.run(a)); },
  down(db) { db.exec('DROP TABLE IF EXISTS entitlement_overrides; DROP TABLE IF EXISTS entitlement_usage_ledger; DROP TABLE IF EXISTS entitlement_decisions; DROP TABLE IF EXISTS entitlement_policies; DROP TABLE IF EXISTS service_contract_history; DROP TABLE IF EXISTS service_contract_renewals; DROP TABLE IF EXISTS service_contract_allowances; DROP TABLE IF EXISTS service_contract_exclusions; DROP TABLE IF EXISTS service_contract_lines; DROP TABLE IF EXISTS service_contract_sites; DROP TABLE IF EXISTS service_contract_assets; DROP TABLE IF EXISTS service_contract_products; DROP TABLE IF EXISTS service_contracts;'); }
};
