'use strict';
import crypto from 'node:crypto';
const uid = (prefix) => `${prefix}_${crypto.randomUUID()}`, ts = () => new Date().toISOString();
export class SignatureError extends Error { constructor(message, code) { super(message); this.code = code; } }
const keyOf = (input = {}) => input.idempotencyKey || input.idempotency_key || null;
export class ElectronicSignatureService {
  constructor(dialect) { this.dialect = dialect; }
  provider(input, ctx = {}) { const companyId = ctx.companyId || input.companyId; if (!companyId) throw new SignatureError('active company is required', 'COMPANY_SCOPE_REQUIRED'); const p = { id: uid('sigprov'), companyId }; this.dialect.prepare("INSERT INTO signature_providers VALUES(?,?,?,'enabled',?,?)").run(p.id, p.companyId, input.name || 'local-simulator', input.secretReference || null, ts()); return p; }
  get(requestId, companyId = null) { const row = this.dialect.prepare('SELECT * FROM signature_requests WHERE id=?').get(requestId) || null; if (row && companyId && row.company_id !== companyId) throw new SignatureError('signature request is outside active company', 'COMPANY_SCOPE_DENIED'); return row; }
  list(ctx = {}) { return this.dialect.prepare('SELECT * FROM signature_requests WHERE company_id=? ORDER BY created_at DESC').all(ctx.companyId); }
  create(input, ctx = {}) { const companyId = ctx.companyId || input.companyId; if (!companyId || !input.sourceEntity || !input.sourceRecordId || !input.sourceContent) throw new SignatureError('company, immutable source and record are required', 'SOURCE_REQUIRED'); const idem = keyOf(input), old = idem && this.dialect.prepare('SELECT * FROM signature_requests WHERE idempotency_key=?').get(idem); if (old) { if (old.company_id !== companyId) throw new SignatureError('idempotency key belongs to another company', 'COMPANY_SCOPE_DENIED'); return old; } if (input.providerId && !this.dialect.prepare("SELECT 1 FROM signature_providers WHERE id=? AND company_id=? AND status='enabled'").get(input.providerId, companyId)) throw new SignatureError('enabled provider not found', 'PROVIDER_NOT_AVAILABLE'); const request = { id: uid('sigreq'), companyId }, stamp = ts(), checksum = crypto.createHash('sha256').update(input.sourceContent).digest('hex'); this.dialect.prepare("INSERT INTO signature_requests VALUES(?,?,?,?,?,?,'draft',?,?,?,?,?,?)").run(request.id, request.companyId, input.sourceEntity, input.sourceRecordId, input.sourceFileId || null, checksum, input.providerId || null, input.correlationId || ctx.correlationId || uid('corr'), idem, ctx.userId || 'system', stamp, stamp); return this.get(request.id, companyId); }
  addSigner(requestId, input, ctx = {}) { const request = this.get(requestId, ctx.companyId); if (!request) throw new SignatureError('request not found', 'REQUEST_NOT_FOUND'); if (request.status !== 'draft') throw new SignatureError('signers can only be changed in draft', 'INVALID_SIGNATURE_STATE'); if (!input.email || !input.name || !Number.isInteger(Number(input.order)) || Number(input.order) < 1) throw new SignatureError('email, name and positive signer order are required', 'INVALID_SIGNER'); const signer = { id: uid('signer') }; this.dialect.prepare("INSERT INTO signature_signers VALUES(?,?,?,?,?,'pending')").run(signer.id, requestId, input.email, input.name, Number(input.order)); return signer; }
  #state(requestId, status, ctx = {}) { const request = this.get(requestId, ctx.companyId); if (!request) throw new SignatureError('request not found', 'REQUEST_NOT_FOUND'); this.dialect.prepare('UPDATE signature_requests SET status=?,updated_at=? WHERE id=?').run(status, ts(), requestId); return this.get(requestId, request.company_id); }
  prepare(requestId, ctx = {}) { const r = this.get(requestId, ctx.companyId); if (!r || r.status !== 'draft') throw new SignatureError('only draft request can be prepared', 'INVALID_SIGNATURE_STATE'); if (!this.dialect.prepare('SELECT 1 FROM signature_signers WHERE request_id=?').get(requestId)) throw new SignatureError('at least one signer is required', 'SIGNERS_REQUIRED'); return this.#state(requestId, 'prepared', ctx); }
  send(requestId, ctx = {}) { const r = this.get(requestId, ctx.companyId); if (!r || r.status !== 'prepared') throw new SignatureError('only prepared request can be sent', 'INVALID_SIGNATURE_STATE'); return this.#state(requestId, 'sent', ctx); }
  event(requestId, type, eventKey) { if (eventKey && this.dialect.prepare('SELECT 1 FROM signature_events WHERE event_key=?').get(eventKey)) return false; this.dialect.prepare('INSERT INTO signature_events VALUES(?,?,?,?,?)').run(uid('sigevt'), requestId, type, eventKey || uid('event'), ts()); return true; }
  view(requestId, eventKey, ctx = {}) { const r = this.get(requestId, ctx.companyId); if (!r || !['sent', 'viewed'].includes(r.status)) throw new SignatureError('request is not available for viewing', 'INVALID_SIGNATURE_STATE'); this.event(requestId, 'viewed', eventKey); return this.#state(requestId, 'viewed', ctx); }
  sign(requestId, order, eventKey, ctx = {}) { const r = this.get(requestId, ctx.companyId); if (!r || !['sent', 'viewed', 'partially_signed'].includes(r.status)) throw new SignatureError('request is not available for signing', 'INVALID_SIGNATURE_STATE'); const signer = this.dialect.prepare('SELECT * FROM signature_signers WHERE request_id=? AND signer_order=?').get(requestId, Number(order)); if (!signer) throw new SignatureError('signer missing', 'SIGNER_NOT_FOUND'); const predecessor = this.dialect.prepare("SELECT 1 FROM signature_signers WHERE request_id=? AND signer_order<? AND status!='signed'").get(requestId, Number(order)); if (predecessor) throw new SignatureError('previous signer must sign first', 'SIGNING_ORDER_REQUIRED'); if (signer.status === 'signed') return this.get(requestId, r.company_id); this.event(requestId, 'signed', eventKey); this.dialect.prepare("UPDATE signature_signers SET status='signed' WHERE id=?").run(signer.id); const pending = this.dialect.prepare("SELECT count(*) n FROM signature_signers WHERE request_id=? AND status!='signed'").get(requestId).n; if (pending) return this.#state(requestId, 'partially_signed', ctx); const complete = this.#state(requestId, 'completed', ctx), checksum = crypto.createHash('sha256').update(`${complete.source_checksum}:signed`).digest('hex'); this.dialect.prepare('INSERT INTO signature_evidence VALUES(?,?,?,?)').run(uid('evidence'), requestId, checksum, ts()); return complete; }
  verify(requestId, ctx = {}) { const r = this.get(requestId, ctx.companyId), e = this.dialect.prepare('SELECT * FROM signature_evidence WHERE request_id=?').get(requestId); if (!r || !e) throw new SignatureError('evidence unavailable', 'EVIDENCE_MISSING'); return { requestId, valid: r.status === 'completed' && e.signed_checksum === crypto.createHash('sha256').update(`${r.source_checksum}:signed`).digest('hex') }; }
}
export const createElectronicSignatureService = (dialect) => new ElectronicSignatureService(dialect);
