import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs'; import http from 'node:http'; import os from 'node:os'; import path from 'node:path';
import { freshInstall, openMigrationDatabase } from '../../database/migration-runner/index.mjs';
import { createPlatformAuthority } from '../../platform-runtime-bridge.mjs';
import { createApiHandler } from '../../platform/api/index.mjs';

test('BUILD-07C/D real Chromium renders scoped service workspaces', async () => {
 const dbPath=path.join(os.tmpdir(),`octagon-b07-browser-${Date.now()}.db`);await freshInstall({dbPath});const dialect=openMigrationDatabase(dbPath),authority=createPlatformAuthority(dialect),ctx={companyId:'default',userId:'browser-user'};
 const contract=authority.serviceEntitlementService.createContract({customerId:'browser-customer',contractNumber:'BROWSER-1',startDate:'2026-01-01',endDate:'2026-12-31',idempotencyKey:'browser-contract'},ctx);
 const provider=authority.electronicSignatureService.provider({name:'sim'},ctx);authority.electronicSignatureService.create({sourceEntity:'service_contract',sourceRecordId:contract.id,sourceContent:'browser snapshot',providerId:provider.id,idempotencyKey:'browser-signature'},ctx);
 const api=createApiHandler({dialect,prefix:'/api/v1',actionExecutor:authority.actionExecutor,resolveContext:()=>({...ctx,tenantId:'default',branchId:'default',actorType:'user',correlationId:'browser-proof'}),authorize:()=>({allowed:true})});
 const routes={ '/service_contracts':'views/service_contracts.html','/entitlements':'views/entitlements.html','/electronic_signatures':'views/electronic_signatures.html' };
 const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://127.0.0.1');if(routes[url.pathname]){res.writeHead(200,{'Content-Type':'text/html'});res.end(fs.readFileSync(path.resolve(routes[url.pathname])));return;}if(api(req,res,url))return;res.writeHead(404);res.end();});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const browser=await (await import('puppeteer')).default.launch({headless:'new',args:['--no-sandbox','--disable-dev-shm-usage']});try{const base=`http://127.0.0.1:${server.address().port}`,page=await browser.newPage();await page.goto(base+'/service_contracts',{waitUntil:'domcontentloaded',timeout:10000});const action=async(id,body)=>page.evaluate(async([id,body])=>{const r=await fetch('/api/v1/action/'+id,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json()},[id,body]);for(const [state,key] of [['validate','v'],['submit','s'],['approve','a'],['activate','x']])assert.equal((await action('service_contract:'+state,{contract_id:contract.id,idempotency_key:key})).success,true);const policy=authority.serviceEntitlementService.createPolicy({contractId:contract.id,name:'browser'},ctx);authority.serviceEntitlementService.publishPolicy(policy.id,ctx);const decision=authority.serviceEntitlementService.evaluate({customerId:'browser-customer',serviceDate:'2026-08-02'},ctx);assert.equal((await action('entitlement:consume',{decision_id:decision.id,quantity:1,idempotency_key:'u'})).success,true);authority.electronicSignatureService.addSigner((await authority.electronicSignatureService.list(ctx))[0].id,{email:'one@test',name:'One',order:1},ctx);authority.electronicSignatureService.addSigner((await authority.electronicSignatureService.list(ctx))[0].id,{email:'two@test',name:'Two',order:2},ctx);const req=(await authority.electronicSignatureService.list(ctx))[0];authority.electronicSignatureService.prepare(req.id,ctx);authority.electronicSignatureService.send(req.id,ctx);authority.electronicSignatureService.sign(req.id,1,'one',ctx);authority.electronicSignatureService.sign(req.id,2,'two',ctx);assert.equal(authority.electronicSignatureService.verify(req.id,ctx).valid,true);await page.close();}finally{await browser.close();await new Promise(resolve=>server.close(resolve));dialect.close();fs.unlinkSync(dbPath);}
});
